### PR TITLE
Converting table at docs from HTML code to GHFM

### PR DESCRIPTION
**Pull request by saulotoledo**
Converting table at docs from HTML code to GHFM as requided on issue  #10 .

### CODE REVIEW

**Comment by GeeH** [comment]
Thank you so much for this PR @saulotoledo - as @froschdesign says, if you could remove the HTML entities I can merge this asap.

Thanks again!

**Comment by saulotoledo** [comment]
@froschdesign, @GeeH, thank you for your return.
The entities are now removed.

Thanks!

**Comment by GeeH** [comment]
I'm good to merge this if you are @froschdesign?

**Comment by froschdesign** [comment]
@GeeH
All fine. Go!

**Comment by weierophinney** [comment]
I'm currently working on documentation updates for a 2.6.0 release, and this is timely; I'd just hit the tables, and decided to skip them and come back to them later. :smile: 

I'm going to merge locally, and push with a larger PR hitting the rest of the documentation issues.

Thanks, @saulotoledo !

**Comment by saulotoledo** [comment]
Thank you, @weierophinney ! I hope it helps.
I have pushed another PR before noticing your self-assignments ( #15 ) .
If I find another of these not assigned issues I will push some more PRs in my free time. Let me know if there is something I can do.

**Comment by weierophinney** [comment]
@saulotoledo I started working on these yesterday, but forgot to assign them first. :) There's a ton of rewriting necessary, unfortunately, as they were written before the route matching capabilities were made standalone. I'm a little over half-way done, and should finish up in the next few hours.

In the meantime, go ahead and tackle other components!

**Pull request merged**
