### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by merlindorin**
Suggest text based compoments useful for table and figlet with the appropriate decorator.

### CODE REVIEW

**Comment by merlindorin** [comment]
Pull request directly on master, the suggest in composer.json has no BC

**Comment by gianarb** [comment]
:+1:

**Comment by weierophinney** [comment]
@Maks3w Please merge to develop as well.

**Comment by Maks3w** [comment]
It's merged, bug GH does not display the commit in the PR

**Pull request merged**
